          //hacer login//
get http://localhost:3001/api/login/
Content-Type: application/json

{
  "identificacion": 1059696994,
  "contrasena_hash": "134679"
}
###
          //prueba usuarios//
get http://localhost:3001/api/usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWNhY2lvbiI6IjE2MTYxNiIsIm5vbWJyZSI6Im9wZXJhZG9yIDE2Iiwicm9sX2lkIjoyLCJpYXQiOjE3NzYwNjY4NDMsImV4cCI6MTc3NjA2ODY0M30.aADknFHU5h-JH_MxCP_qse-hKJrg4zknN30-vFSDHrc
###

get http://localhost:3001/api/usuarios/171717
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWNhY2lvbiI6IjE2MTYxNiIsIm5vbWJyZSI6Im9wZXJhZG9yIDE2Iiwicm9sX2lkIjoyLCJpYXQiOjE3NzYwNjY4NDMsImV4cCI6MTc3NjA2ODY0M30.aADknFHU5h-JH_MxCP_qse-hKJrg4zknN30-vFSDHrc

###
post http://localhost:3001/api/usuarios/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWNhY2lvbiI6IjEwNTk2OTY5OTQiLCJub21icmUiOiJqdWFuIGlnbmFjaW8gYmV0YW5jdXIiLCJyb2xfaWQiOjEsImlhdCI6MTc3NjA2ODg5OSwiZXhwIjoxNzc2MDcwNjk5fQ.Xrri9Q3BCmCzfGvUF9kd58nqHhsI7PIf3U_2ybw3ovY

{
  "nombre": "operador 17",
  "identificacion": "171717",
  "email": "171717@gmail.com"
}

###
put http://localhost:3001/api/usuarios/171717
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWNhY2lvbiI6IjEwNTk2OTY5OTQiLCJub21icmUiOiJqdWFuIGlnbmFjaW8gYmV0YW5jdXIiLCJyb2xfaWQiOjEsImlhdCI6MTc3NjA2ODg5OSwiZXhwIjoxNzc2MDcwNjk5fQ.Xrri9Q3BCmCzfGvUF9kd58nqHhsI7PIf3U_2ybw3ovY

{
  "activo": false
}

###
DELETE http://localhost:3001/api/usuarios/161616
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWNhY2lvbiI6IjEwNTk2OTY5OTQiLCJub21icmUiOiJqdWFuIGlnbmFjaW8gYmV0YW5jdXIiLCJyb2xfaWQiOjEsImlhdCI6MTc3NjA2Njk5NSwiZXhwIjoxNzc2MDY4Nzk1fQ.xwToR7tTwg0jMS_wln7B-jc4ddcYlL3-PRfwUvUwP6Q

###

          //Pruebas roles//

get http://localhost:3001/api/roles/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJ1c3VhcmlvIDMiLCJyb2xfaWQiOjMsImlhdCI6MTc3NjA1OTQ0MCwiZXhwIjoxNzc2MDYxMjQwfQ.VJ9YfGoAP1DyO4c9RPyWuuHDcJCGET8iRoIAdXY0BQk
###
get http://localhost:3001/api/roles/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJ1c3VhcmlvIDMiLCJyb2xfaWQiOjMsImlhdCI6MTc3NjA1OTQ0MCwiZXhwIjoxNzc2MDYxMjQwfQ.VJ9YfGoAP1DyO4c9RPyWuuHDcJCGET8iRoIAdXY0BQk
###

post http://localhost:3001/api/roles/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJqdWFuIGlnbmFjaW8gYmV0YW5jdXIiLCJyb2xfaWQiOjEsImlhdCI6MTc3NTk3ODY0MSwiZXhwIjoxNzc1OTgwNDQxfQ.GKzfyWyb0EAAyM12CwlShvQN-DJ0kLBCsAWcL8aiPOg

{
  "nombre": ,
  "activo": 12
}

###
          //nuevo usuario//

post http://localhost:3001/api/nuevo_usuario/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWNhY2lvbiI6IjE2MTYxNiIsIm5vbWJyZSI6Im9wZXJhZG9yIDE2Iiwicm9sX2lkIjoyLCJpYXQiOjE3NzYwNjM3NTMsImV4cCI6MTc3NjA2NTU1M30.PqolWhbcY8yR-OgcRumq5qdY-szUBA1xxAYn577nVrU

{
  "nombre": "operador 18",
  "identificacion": "181818",
  "email": "181818@gmail.com",
  "telefono": 3014778621,
  "contrasena_hash": "181818",
  "rol_id": 1
}
###

        //nueva venta//

post http://localhost:3001/api/nueva_venta/
Content-Type: application/json
Authorization: Bearer eyJbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJqdWFuIGlnbmFjaW8gYmV0YW5jdXIiLCJyb2xfaWQiOjEsImlhdCI6MTc3NTk2MjU5NCwiZXhwIjoxNzc1OTY0Mzk0fQ.xK8xgAH1X_UtZN2NdGg4GpUqlfXtivxDnOy5kdZhvcI

{
  "usuario_id": 1,
  "cliente_id": 3,
  "metodo_pago": "efectivo",
  "detalles": [
    {
      "producto_id": 12,
      "cantidad": 2
    }
  ]
}
###

          //nuevo producto//

post http://localhost:3001/api/nuevo_producto/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJqdWFuIGlnbmFjaW8gYmV0YW5jdXIiLCJyb2xfaWQiOjEsImlhdCI6MTc3NTk2MjU5NCwiZXhwIjoxNzc1OTY0Mzk0fQ.xK8xgAH1X_UtZN2NdGg4GpUqlfXtivxDnOy5kdZhvcI

{
  "nombre": "frutas",
  "descripcion": "reloj para ver la hora",
  "precio": 60000,
  "categoria_id": 2
}
###

            //iniciar renta//

post http://localhost:3001/api/iniciar_renta/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJqdWFuIGlnbmFjaW8gYmV0YW5jdXIiLCJyb2xfaWQiOjEsImlhdCI6MTc3NTk2MjU5NCwiZXhwIjoxNzc1OTY0Mzk0fQ.xK8xgAH1X_UtZN2NdGg4GpUqlfXtivxDnOy5kdZhvcI

{
  "cliente_id": 3,
  "usuario_id": 4,
  "fecha_inicio": "2026-04-09T01:30:00-05:00",
  "fecha_fin": "2026-04-09T02:30:00-05:00",
  "metodo_pago": "efectivo",
  "dispositivos":[
    {
      "dispositivo_id": 3
    }
  ]
}
###

              //crear deuda//

post http://localhost:3001/api/crear_deuda/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJqdWFuIGlnbmFjaW8gYmV0YW5jdXIiLCJyb2xfaWQiOjEsImlhdCI6MTc3NTk2MjU5NCwiZXhwIjoxNzc1OTY0Mzk0fQ.xK8xgAH1X_UtZN2NdGg4GpUqlfXtivxDnOy5kdZhvcI

{
  "cliente_id": 3,
  "origen_tipo": "venta",
  "origen_id": 3,
  "monto_total": 5000,
  "saldo": null
}
###

                //pagar deuda//

post http://localhost:3001/api/pago_deuda/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJqdWFuIGlnbmFjaW8gYmV0YW5jdXIiLCJyb2xfaWQiOjEsImlhdCI6MTc3NTk2MjU5NCwiZXhwIjoxNzc1OTY0Mzk0fQ.xK8xgAH1X_UtZN2NdGg4GpUqlfXtivxDnOy5kdZhvcI

{
  "deuda_id": 10,
  "monto": 2500,
  "metodo_pago": "tranferencia",
  "monto_total": 5000
}
###
