          //hacer login//
post http://localhost:3001/api/login/
Content-Type: application/json

{
  "identificacion":1059696994 ,
  "contrasena_hash": "134679"
}
###

          //prueba usuarios//
get http://localhost:3001/api/usuarios/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWNhY2lvbiI6IjEwNTk2OTY5OTQiLCJub21icmUiOiJqdWFuIGlnbmFjaW8gYmV0YW5jdXIiLCJyb2xfaWQiOjEsImlhdCI6MTc3NzIzNzg2MiwiZXhwIjoxNzc3MjM5NjYyfQ.QIkPbOv1nuY--eQZCk1jbkRaix6YiLjnhGx6vPhDmeI
###
          //prueba ventas//

GET http://localhost:3001/api/ventas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWNhY2lvbiI6IjEwNTk2OTY5OTQiLCJub21icmUiOiJqdWFuIGlnbmFjaW8gYmV0YW5jdXIiLCJyb2xfaWQiOjEsImlhdCI6MTc3NzIzNzg2MiwiZXhwIjoxNzc3MjM5NjYyfQ.QIkPbOv1nuY--eQZCk1jbkRaix6YiLjnhGx6vPhDmeI

###

          //nuevo usuario//

post http://localhost:3001/api/nuevo_usuario/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWNhY2lvbiI6IjEwNTk2OTY5OTQiLCJub21icmUiOiJqdWFuIGlnbmFjaW8gYmV0YW5jdXIiLCJyb2xfaWQiOjEsImlhdCI6MTc3NzIzOTkxNywiZXhwIjoxNzc3MjQxNzE3fQ.LMLVtBaPANceKgQfNQf7lF62OtYiwvmSokGOOmkIw04

{
  "nombre": "duban",
  "identificacion": "9911557",
  "email": "duban@gmail.com",
  "telefono": 30179854648,
  "contrasena_hash": "joseduban",
  "rol_id": 1
}

###

        //mostrar usuario//

get http://localhost:3001/api/usuarios/280426
Authorization: Bearer 


###


        //nueva venta//

post http://localhost:3001/api/nueva_venta/
Content-Type: application/json
Authorization: Bearer 

{
  "usuario_id": ,
  "metodo_pago": ,
  "detalles": [
    {
      "producto_id": ,
      "cantidad": 
    }
  ]
}


###

          //nuevo producto//


post http://localhost:3001/api/nuevo_producto/
Content-Type: application/json
Authorization: Bearer

{
  "nombre": "",
  "descripcion": "",
  "precio": ,
  "categoria_id": 
}


###

            //iniciar renta//

post http://localhost:3001/api/iniciar_renta/
Content-Type: application/json
Authorization: Bearer 

{
  "cliente_id": ,
  "usuario_id": ,
  "fecha_inicio": "2026-04-09T01:30:00-05:00",
  "fecha_fin": "2026-04-09T02:30:00-05:00",
  "metodo_pago": "efectivo",
  "dispositivos":[
    {
      "dispositivo_id": 
    }
  ]
}
###

              //crear deuda//


post http://localhost:3001/api/crear_deuda/
Content-Type: application/json
Authorization: Bearer 

{
  "cliente_id": ,
  "origen_tipo": "",
  "origen_id":
}
###

                //pagar deuda//

post http://localhost:3001/api/pago_deuda/
Content-Type: application/json
Authorization: Bearer 

{
  "deuda_id": ,
  "monto": ,
  "metodo_pago": "tranferencia",
  "monto_total": 
}
