name: "backend"

on:
  push:
    paths: 
      - 'backend/**'

jobs:
  
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
    - name: "pruebas de checkout"
      uses: actions/checkout@v4
    
    - name: "prueba de version"
      uses: actions/setup-node@v4
      with:
        node-version: 26.2.0
    
    - name: "confirmando ubicacion del backend"
      run: |
        pwd
        ls -la
        find . -name package.json

    - name: "Install pnpm"
      uses: pnpm/action-setup@v4
      with:
        version: 10.33.4

    - name: "prueba de instalacion de dependencias"
      run: pnpm i

    - name: "prueba de eslinter"
      run: pnpm lint

    - name: Verificar secrets
      run: |
        if [ -z "$DATABASE_URL" ]; then
          echo "DATABASE_URL VACIA"
        else
          echo "DATABASE_URL PRESENTE"
        fi
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      
    - name: "prueba de test" 
      run: pnpm test
      env:
        PORT: ${{ secrets.PORT }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
        JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
        JWT_REFRESH_EXPIRES_IN: ${{ secrets.JWT_REFRESH_EXPIRES_IN }}